### ISSUE TITLE
Failure in t/perl5-compat.t and no plan found.

### ISSUE THREAD

**Issue by cschwenz** [cosimo/perl6-digest-md5#11]
$ panda install Digest::MD5
    ==> Fetching Digest::MD5
    ==> Building Digest::MD5
    ==> Testing Digest::MD5
    t/0-load-module.t .. 
    All 1 subtests passed 
    Too few positionals passed; expected 4 arguments but got 3
      in block  at /home/cschwenz/.panda-work/1442071906_1/lib/Digest/MD5.pm:37
      in sub infix:<⊞> at /home/cschwenz/.panda-work/1442071906_1/lib/Digest/MD5.pm:7
      in sub md5-block at /home/cschwenz/.panda-work/1442071906_1/lib/Digest/MD5.pm:45
      in sub md5 at /home/cschwenz/.panda-work/1442071906_1/lib/Digest/MD5.pm:53
      in method md5_hex at /home/cschwenz/.panda-work/1442071906_1/lib/Digest/MD5.pm:57
      in block <unit> at t/perl5-compat.t:18

    t/perl5-compat.t ... 
    No subtests run 

    Test Summary Report
    -------------------
    t/0-load-module.t (Wstat: 0 Tests: 1 Failed: 0)
      Parse errors: No plan found in TAP output
    t/perl5-compat.t (Wstat: 0 Tests: 0 Failed: 0)
      Parse errors: No plan found in TAP output
    Files=2, Tests=1, 38 wallclock secs ( 0.11 usr  0.02 sys + 36.89 cusr  0.87 csys = 37.89 CPU)
    Result: FAIL
    test stage failed for Digest::MD5: Tests failed
      in method throw at /home/cschwenz/.rakudobrew/moar-nom/install/share/perl6/runtime/CORE.setting.moarvm:1
      in method install at /home/cschwenz/.rakudobrew/moar-nom/install/share/perl6/site/lib/Panda.pm:142
      in method resolve at /home/cschwenz/.rakudobrew/moar-nom/install/share/perl6/site/lib/Panda.pm:219
      in sub MAIN at /home/cschwenz/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/panda:18
      in block <unit> at /home/cschwenz/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/panda:95

    Failure Summary
    ----------------
    Digest::MD5(
      *test stage failed for Digest::MD5: Tests failed)

My perl6 version is:

    $ perl6 --version
    This is perl6 version 2015.07.1-854-g8876f4d built on MoarVM version 2015.08-15-g4b427ed

**Comment by FROGGS** [comment]
I just fixed it with commit 8dc95104ff17df4dfb1c5da0189315735ad1eda8, though you need upgrade your rakudo to get the GLR changes...
Note that this might break your code, because less flattening happens by default.
