### ISSUE TITLE
7 bit "ascii" encoding is too restrictive should be "latin-1"

### ISSUE THREAD

**Issue by dwarring** [cosimo/perl6-digest-md5#17]
The Perl 5 module handles bytes in the range 0-255, e.g.

```
$ perl -MDigest::MD5 -E'say Digest::MD5::md5_hex("Zsófia#")'
b8beb99cf2374c72338deef010076e74
```
Whereas the Perl 6 modules method md5 don't accept input characters in the range 128-255.

```
$ perl6 -MDigest::MD5 -e'say Digest::MD5.new.md5_hex("Zsófia#")'
Error encoding ASCII string: could not encode codepoint 243
  in method md5_hex at lib/Digest/MD5.pm:58
  in block <unit> at -e:1
```
For Perl 5 compatibility, `latin-1` encoding probably works better. All character in the range 0-255 are legal.

**Comment by cosimo** [comment]
PR #19 has been merged, so closing.
