### ISSUE TITLE
t/0-load-module.t fails

### ISSUE THREAD

**Issue by coke** [cosimo/perl6-digest-md5#6]
Test fails in a similar fashion on all rakudo backends

Testing modules/perl6-digest-md5 with /home/coke/sandbox/rakudo-star-daily/star-MoarVM/rakudo-star-daily/install/bin/perl6-m...
t/0-load-module.t .. ok
Cannot call 'postcircumfix:<[ ]>'; none of these signatures match:
:(Any \SELF, int $pos)
:(Any \SELF, int $pos, \assignee)
:(Any \SELF, int $pos, :BIND($BIND)!)
:(Any \SELF, int $pos, Any :SINK($SINK)!, *%other)
:(Any \SELF, int $pos, Any :delete($delete)!, *%other)
:(Any \SELF, int $pos, Any :exists($exists)!, *%other)
:(Any \SELF, int $pos, Any :kv($kv)!, *%other)
:(Any \SELF, int $pos, Any :p($p)!, *%other)
:(Any \SELF, int $pos, Any :k($k)!, *%other)
:(Any \SELF, int $pos, Any :v($v)!, *%other)
:(Any \SELF, Any \pos)
:(Any \SELF, Any \pos, \assignee)
:(Any \SELF, Any \pos, :BIND($BIND)!)
:(Any \SELF, Any \pos, Any :SINK($SINK)!, *%other)
:(Any \SELF, Any \pos, Any :delete($delete)!, *%other)
:(Any \SELF, Any \pos, Any :exists($exists)!, *%other)
:(Any \SELF, Any \pos, Any :kv($kv)!, *%other)
:(Any \SELF, Any \pos, Any :p($p)!, *%other)
:(Any \SELF, Any \pos, Any :k($k)!, *%other)
:(Any \SELF, Any \pos, Any :v($v)!, *%other)
:(Any \SELF, Positional \pos)
:(Any \SELF, Positional \pos, \assignee)
:(Any \SELF, Positional \pos, Any :BIND($BIND)!)
:(Any \SELF, Positional \pos, Any :SINK($SINK)!, *%other)
:(Any \SELF, Positional \pos, Any :delete($delete)!, *%other)
:(Any \SELF, Positional \pos, Any :exists($exists)!, *%other)
:(Any \SELF, Positional \pos, Any :kv($kv)!, *%other)
:(Any \SELF, Positional \pos, Any :p($p)!, *%other)
:(Any \SELF, Positional \pos, Any :k($k)!, *%other)
:(Any \SELF, Positional \pos, Any :v($v)!, *%other)
:(Any \SELF, $block)
:(Any \SELF, $block, \assignee)
:(Any \SELF, $block, Any :BIND($BIND)!)
:(Any \SELF, $block, Any :SINK($SINK)!, *%other)
:(Any \SELF, $block, Any :delete($delete)!, *%other)
:(Any \SELF, $block, Any :exists($exists)!, *%other)
:(Any \SELF, $block, Any :kv($kv)!, *%other)
:(Any \SELF, $block, Any :p($p)!, *%other)
:(Any \SELF, $block, Any :k($k)!, *%other)
:(Any \SELF, $block, Any :v($v)!, *%other)
:(Any \SELF, Whatever)
:(Any \SELF, Whatever, \assignee)
:(Any \SELF, Whatever, Any :BIND($BIND)!)
:(Any \SELF, Whatever, Any :SINK($SINK)!, *%other)
:(Any \SELF, Whatever, Any :delete($delete)!, *%other)
:(Any \SELF, Whatever, Any :exists($exists)!, *%other)
:(Any \SELF, Whatever, Any :kv($kv)!, *%other)
:(Any \SELF, Whatever, Any :p($p)!, *%other)
:(Any \SELF, Whatever, Any :k($k)!, *%other)
:(Any \SELF, Whatever, Any :v($v)!, *%other)
:(Any \SELF, HyperWhatever, *%adv)
:(Any \SELF, HyperWhatever, \assignee, *%adv)
:(Any \SELF)
:(Any \SELF, Any :BIND($BIND)!)
:(Any \SELF, Any :SINK($SINK)!, *%other)
:(Any \SELF, Any :delete($delete)!, *%other)
:(Any \SELF, Any :exists($exists)!, *%other)
:(Any \SELF, Any :kv($kv)!, *%other)
:(Any \SELF, Any :p($p)!, *%other)
:(Any \SELF, Any :k($k)!, *%other)
:(Any \SELF, Any :v($v)!, *%other)
:(Any \SELF is rw, LoL \keys, *%adv)
:(Any \SELF is rw, LoL \keys, \assignee, *%adv)
  in sub md5-block at /home/coke/sandbox/rakudo-star-daily/star-MoarVM/rakudo-star-daily/install/languages/perl6/lib/Digest/MD5.pm:40
  in sub md5 at /home/coke/sandbox/rakudo-star-daily/star-MoarVM/rakudo-star-daily/install/languages/perl6/lib/Digest/MD5.pm:48
  in method md5_hex at /home/coke/sandbox/rakudo-star-daily/star-MoarVM/rakudo-star-daily/install/languages/perl6/lib/Digest/MD5.pm:52
  in block <unit> at t/perl5-compat.t:18

t/perl5-compat.t ... 
No subtests run 

Test Summary Report
-------------------
t/perl5-compat.t (Wstat: 0 Tests: 0 Failed: 0)
  Parse errors: No plan found in TAP output
Files=2, Tests=1,  2 wallclock secs ( 0.02 usr  0.01 sys +  1.43 cusr  0.14 csys =  1.60 CPU)
Result: FAIL

**Comment by FROGGS** [comment]
Works now...
